version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - app_net

  ganache:
    image: trufflesuite/ganache
    container_name: ganache
    ports:
      - "8545:8545"
    command: >
      --accounts=10
      --defaultBalanceEther=1000
      --mnemonic="test test test test test test test test test test test junk"
      --gasLimit=8000000
    networks:
      - app_net

networks:
  app_net:
    driver: bridge